repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: check-case-conflict
      - id: debug-statements
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.8"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/python-poetry/poetry
    rev: "2.1.3"
    hooks:
      - id: poetry-check

  - repo: local
    hooks:
      - id: mypy
        entry: .venv/bin/mypy
        name: mypy
        language: python
        language_version: "3.13"
        args:
          ["--install-types", "--non-interactive", "--ignore-missing-imports"]
        types: [python, pyi]
        exclude: |
          ^(tests|docs|examples)/.*$|
          conftest\.py$
