@startuml Activity Diagram

start

:Пользователь открывает приложение;

if (Пользователь авторизован?) then (да)
  :Показать список чатов;
else (нет)
  :Показать страницу входа;
  if (Есть аккаунт?) then (да)
    :Ввести логин и пароль;
  else (нет)
    :Перейти на страницу регистрации;
    :Создать аккаунт;
  endif
  :Авторизоваться;
  :Показать список чатов;
endif

:Выбрать чат;

:Загрузить историю сообщений;
:Подключиться к Socket.IO;
:Присоединиться к комнате чата;

while (Пользователь в чате?) is (да)
  if (Действие пользователя?) then (отправить сообщение)
    :Ввести текст сообщения;
    :Отправить через Socket.IO;
    :Сохранить в БД;
    :Отобразить сообщение всем участникам;
  else if (выйти из чата) then
    :Вернуться к списку чатов;
  else if (выйти из системы) then
    :Выполнить logout;
    :Перенаправить на страницу входа;
    stop
  endif
endwhile

stop

@enduml